### ISSUE TITLE
ModuleNotFoundError: No module named 'termios' on Windows 10

### ISSUE THREAD

**Issue by TerraVenil** [cs50/submit50#292]
```
C:\Users\terra.venil\Documents>submit50 --help                       
Traceback (most recent call last):
  File "C:\Users\terra.venil\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\terra.venil\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\terra.venil\AppData\Local\Programs\Python\Python310\Scripts\submit50.exe\__main__.py", line 4, in <module>       
  File "C:\Users\terra.venil\AppData\Local\Programs\Python\Python310\lib\site-packages\submit50\__init__.py", line 18, in <module>
    CONFIG_LOADER = __import__("lib50").config.Loader("submit50")
  File "C:\Users\terra.venil\AppData\Local\Programs\Python\Python310\lib\site-packages\lib50\__init__.py", line 20, in <module>   
    from ._api import *
  File "C:\Users\terra.venil\AppData\Local\Programs\Python\Python310\lib\site-packages\lib50\_api.py", line 25, in <module>
    from .authentication import authenticate, logout, run_authenticated
  File "C:\Users\terra.venil\AppData\Local\Programs\Python\Python310\lib\site-packages\lib50\authentication.py", line 8, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'
```

**Comment by rongxin-liu** [comment]
If on Windows, please first install [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install-win10). We recommend choosing the Ubuntu distribution. Then within WSL, follow the instructions to install submit50 and see if that works:
https://cs50.readthedocs.io/submit50/

Alternatively if taking CS50 courses online, best to use [code.cs50.io](code.cs50.io)!
