### ISSUE TITLE
columns is 0 when redirecting output

### ISSUE THREAD

**Issue by kzidane** [cs50/submit50#61]
Looks like [`columns`](https://github.com/cs50/submit50/blob/1e122e51105ef02eff8d2de4db6939e538942175/submit50#L243) is `0` if you redirect output, which causes an exception per https://travis-ci.org/cs50/submit50/jobs/238360420#L479

```
$ submit50 --help > foo
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/kareem/github/cs50/submit50/submit50", line 266, in excepthook
    cprint("Sorry, something's wrong! Let sysadmins@cs50.harvard.edu know!", "yellow")
  File "/home/kareem/github/cs50/submit50/submit50", line 254, in cprint
    termcolor.cprint(textwrap.fill(text, columns), color=color, on_color=on_color, attrs=attrs, **kwargs)
  File "/usr/lib/python3.4/textwrap.py", line 377, in fill
    return w.fill(text)
  File "/usr/lib/python3.4/textwrap.py", line 349, in fill
    return "\n".join(self.wrap(text))
  File "/usr/lib/python3.4/textwrap.py", line 340, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/lib/python3.4/textwrap.py", line 234, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width 0 (must be > 0)

Original exception was:
Traceback (most recent call last):
  File "/home/kareem/.virtualenvs/submit50/bin/submit50", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/kareem/github/cs50/submit50/submit50", line 524, in <module>
    main()
  File "/home/kareem/github/cs50/submit50/submit50", line 90, in main
    usage()
  File "/home/kareem/github/cs50/submit50/submit50", line 485, in usage
    cprint("Usage: submit50 problem")
  File "/home/kareem/github/cs50/submit50/submit50", line 254, in cprint
    termcolor.cprint(textwrap.fill(text, columns), color=color, on_color=on_color, attrs=attrs, **kwargs)
  File "/usr/lib/python3.4/textwrap.py", line 377, in fill
    return w.fill(text)
  File "/usr/lib/python3.4/textwrap.py", line 349, in fill
    return "\n".join(self.wrap(text))
  File "/usr/lib/python3.4/textwrap.py", line 340, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/lib/python3.4/textwrap.py", line 234, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width 0 (must be > 0)
```

Perhaps we shouldn't rely on `get_terminal_size`'s fallback value and just hard-code `column or 80`?

**Comment by dmalan** [comment]
Hm, I see different behavior in CS50 CLI: even when redirecting, I get back a non-0 `columns`. I wonder if it's because it's running in a non-terminal environment? Though per https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size, the default `fallback` is 80. Want to try https://github.com/cs50/submit50/pull/64? If that doesn't work, I can just check for 0 and change to 80.

**Comment by kzidane** [comment]
Looks good per https://travis-ci.org/cs50/submit50/builds/239062179!
