### ISSUE TITLE
when doing local dev (e.g., in cli50), can't run ./submit50 without package itself being installed

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#62]
```
$ ../submit50 test
Traceback (most recent call last):
  File "../submit50", line 31, in <module>
    __version__ = get_distribution("submit50").version
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 557, in get_distribution
    dist = get_provider(dist)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 431, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'submit50' distribution was not found and is required by the application
```

**Comment by kzidane** [comment]
This is the expected behavior, and its a price we pay for being able to have version number in one place. But I don't think it's that bad actually, since `submit50` is not standalone anyway. Even if you were able to run it directly (without installation), it'd still crash until you install the dependencies.

**Comment by dmalan** [comment]
`python setup.py develop`
