### ISSUE TITLE
Could not find a suitable TLS CA certificate bundle

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#75]
In CS50 CLI, `submit50` works okay after installing dependencies manually via `pip`, but not via `python setup.py develop`, per below.

```
# python setup.py develop
...

# ./submit50 develop -v
Traceback (most recent call last):
  File "../submit50", line 532, in <module>
    main()
  File "../submit50", line 68, in main
    res = requests.get("https://cs50.me/version")
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/requests-2.17.3-py3.6.egg/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/requests-2.17.3-py3.6.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/requests-2.17.3-py3.6.egg/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/requests-2.17.3-py3.6.egg/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/requests-2.17.3-py3.6.egg/requests/adapters.py", line 407, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/requests-2.17.3-py3.6.egg/requests/adapters.py", line 226, in cert_verify
    "invalid path: {0}".format(cert_loc))
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/certifi-2017.4.17-py3.6.egg/certifi/cacert.pem
```

**Comment by kzidane** [comment]
So the problem seems to be that `easy_install`, which is invoked by `python setup.py develop` to install the package and its dependencies, mistakenly thinks one of the dependency packages, `certifi`, can stay zipped after getting installed, and still work.

Unfortunately, it seems `requests` tries to access a resource from this package, assuming it's a directory (unzipped), which throws the `invalid path` error.

One solution might be using

```
$ pip install -e .
```

instead of

```
python setup.py develop
```

to install package in dev mode, since `pip` seems to always unzip packages per https://stackoverflow.com/a/2090124/1797347!

See also: http://peak.telecommunity.com/DevCenter/setuptools#setting-the-zip-safe-flag!

```
# pip install -e .
Obtaining file:///root
Collecting backports.shutil_get_terminal_size (from submit50==2.2.0)
  Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting pexpect>=4.0 (from submit50==2.2.0)
  Downloading pexpect-4.2.1-py2.py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 57kB/s 
Collecting requests (from submit50==2.2.0)
  Downloading requests-2.17.3-py2.py3-none-any.whl (87kB)
    100% |████████████████████████████████| 92kB 53kB/s 
Collecting six (from submit50==2.2.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting termcolor (from submit50==2.2.0)
  Downloading termcolor-1.1.0.tar.gz
Collecting ptyprocess>=0.5 (from pexpect>=4.0->submit50==2.2.0)
  Downloading ptyprocess-0.5.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->submit50==2.2.0)
  Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB)
    100% |████████████████████████████████| 378kB 44kB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests->submit50==2.2.0)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 57kB/s 
Collecting idna<2.6,>=2.5 (from requests->submit50==2.2.0)
  Downloading idna-2.5-py2.py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 40kB/s 
Collecting urllib3<1.22,>=1.21.1 (from requests->submit50==2.2.0)
  Downloading urllib3-1.21.1-py2.py3-none-any.whl (131kB)
    100% |████████████████████████████████| 133kB 49kB/s 
Installing collected packages: backports.shutil-get-terminal-size, ptyprocess, pexpect, certifi, chardet, idna, urllib3, requests, six, termcolor, submit50
  Running setup.py install for termcolor ... done
  Running setup.py develop for submit50
Successfully installed backports.shutil-get-terminal-size-1.0.0 certifi-2017.4.17 chardet-3.0.4 idna-2.5 pexpect-4.2.1 ptyprocess-0.5.1 requests-2.17.3 six-1.10.0 submit50 termcolor-1.1.0 urllib3-1.21.1
root@f0b68cf7de87:~ (develop)# submit50 
You have an old version of git. Install version 2.7 or later, then re-run submit50!
root@f0b68cf7de87:~ (develop)# 
```
