### ISSUE TITLE
catch requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by dmalan** [cs50/submit50#83]
E.g., when no internet:

```
$ submit50 develop -v
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../submit50", line 514, in <module>
    main()
  File "../submit50", line 120, in main
    submit("submit50", args["problem"])
  File "../submit50", line 355, in submit
    headers = requests.get("https://api.github.com/").headers
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
Sorry, something's wrong! Let sysadmins@cs50.harvard.edu know!
Submission cancelled.
```

**Comment by dmalan** [comment]
https://github.com/cs50/submit50/commit/f561c416b8045ec0fc27b69c6c6e468fe3d10eda
